### ISSUE TITLE
 Handling Empty Private Message Input

### ISSUE THREAD

**Issue by relaxwenj** [ZhangTerrence/nexus#25]
Attempting to send an empty string in a private message conversation causes the application to crash.

**Comment by ZhangTerrence** [comment]
Ah I think I know. Try adding validateString to _message in createMessage validator. It’s crashing cause Mongo is trying to store an empty string when it is defined as required in the schema.

**Comment by ZhangTerrence** [comment]
This will make it required for a message to have content in order to be sent but I think that is fine.

**Comment by relaxwenj** [comment]
Oh i see. Will try later. Thanks!
