### ISSUE TITLE
Missing Return Links on Channel and Private Message Pages

### ISSUE THREAD

**Issue by relaxwenj** [ZhangTerrence/nexus#44]
When navigating to a channel's page within a server, it should have a URL link that allows users to return to the server's main page. Similarly, upon opening a private message conversation, there should be a URL link to return to the friend's page.

**Comment by ZhangTerrence** [comment]
Doesn't the channel page already have this? And in the private message page, the links to both users are at the top. It doesn't look good but it's there.

**Comment by relaxwenj** [comment]
I just checked that the return link to the server's page has been added. But the return link for the private message page is still needed.

**Comment by ZhangTerrence** [comment]
The return link is the user link. The reason I didn't make the link directly go to friends page but instead the profile page is because we can't see another users friend page and the current user can just go to their friends page from their profile page.

**Comment by ZhangTerrence** [comment]
I don't think QOL changes are needed right now, I'm specifically looking for things that cause the code to go boom.

**Comment by ZhangTerrence** [comment]
If our program crashes in any way that's like -10

**Comment by ZhangTerrence** [comment]
Of course if any link does cause the program to crash please tell me

**Comment by relaxwenj** [comment]
Sure. Will try to run the test and find the crash.
